### ISSUE TITLE
very fast, but stops & starts.

### ISSUE THREAD

**Issue by cutieQue** [MoonS3c/LazyLeech#1]
this isnt really an issue just something for people to not worry about, LazyLeech Combo Leecher v2 is very fast, but also that means there will be stops on & off. this could be an error, or something else. idk.

**Comment by I2rys** [comment]
> this isnt really an issue just something for people to not worry about, LazyLeech Combo Leecher v2 is very fast, but also that means there will be stops on & off. this could be an error, or something else. idk.

This gives me an idea, I should put a delay because It's so fast in requesting and It might crash.
